/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'play_flutter';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String LIKE = 'assets/animations/like.flr';
  static const String MUYU_1 = 'assets/audio/muyu_1.mp3';
  static const String MUYU_2 = 'assets/audio/muyu_2.mp3';
  static const String MUYU_3 = 'assets/audio/muyu_3.mp3';
  static const String MUYU = 'assets/basics_learn/images/muyu.png';
  static const String MUYU2 = 'assets/basics_learn/images/muyu2.png';
  static const String APPLICATION_ICON = 'assets/images/application_icon.png';
  static const String APPLICATION_ICON3 = 'assets/images/application_icon3.png';
  static const String BG_LOGIN = 'assets/images/bg_login.png';
  static const String HOME_SECOND_FLOOR_BUILDER = 'assets/images/home_second_floor_builder.png';
  static const String LOGIN_LOGO = 'assets/images/login_logo.png';
  static const String LOGO_WECHAT = 'assets/images/logo_wechat.png';
  static const String LOGO_WEIBO = 'assets/images/logo_weibo.png';
  static const String RANKING_INTEGRAL = 'assets/images/ranking_integral.png';
  static const String RANKING_TOP_BG = 'assets/images/ranking_top_bg.png';
  static const String SHARE_QRCODE = 'assets/images/share_qrcode.png';
  static const String SPLASH_ANDROID = 'assets/images/splash_android.png';
  static const String SPLASH_BG = 'assets/images/splash_bg.png';
  static const String SPLASH_BG_DARK = 'assets/images/splash_bg_dark.png';
  static const String SPLASH_FLUTTER = 'assets/images/splash_flutter.png';
  static const String SPLASH_FUN = 'assets/images/splash_fun.png';
  static const String USER_AVATAR = 'assets/images/user_avatar.png';
  static const String WECHAT_PUBLIC_408 = 'assets/images/wechat_public_408.jpg';
  static const String WECHAT_PUBLIC_409 = 'assets/images/wechat_public_409.jpg';
  static const String WECHAT_PUBLIC_410 = 'assets/images/wechat_public_410.jpg';
  static const String WECHAT_PUBLIC_411 = 'assets/images/wechat_public_411.jpg';
  static const String WECHAT_PUBLIC_413 = 'assets/images/wechat_public_413.jpg';
  static const String WECHAT_PUBLIC_414 = 'assets/images/wechat_public_414.jpg';
  static const String WECHAT_PUBLIC_415 = 'assets/images/wechat_public_415.jpg';
  static const String WECHAT_PUBLIC_416 = 'assets/images/wechat_public_416.jpg';
  static const String WECHAT_PUBLIC_417 = 'assets/images/wechat_public_417.jpg';
  static const String WECHAT_PUBLIC_420 = 'assets/images/wechat_public_420.jpg';
  static const String WECHAT_PUBLIC_421 = 'assets/images/wechat_public_421.jpg';
  static const String WECHAT_PUBLIC_427 = 'assets/images/wechat_public_427.jpg';
  static const String WECHAT_PUBLIC_428 = 'assets/images/wechat_public_428.jpg';
  static const String WECHAT_PUBLIC_434 = 'assets/images/wechat_public_434.jpg';
  static const String COLLECT_SUCCESS = 'assets/lottie/collect_success.json';
  static const String LOTTIE_COMMON_LOAD = 'assets/lottie/lottie_common_load.json';
  static const String PAGE_LOADING_ANIM = 'assets/lottie/page_loading_anim.json';
  static const String REFRESH_EMPTY_PAGE = 'assets/lottie/refresh_empty_page.json';
  static const String REFRESH_ERROR = 'assets/lottie/refresh_error.json';
  static const String REFRESH_FOOTER = 'assets/lottie/refresh_footer.json';
  static const String REFRESH_FOOTERR = 'assets/lottie/refresh_footerr.json';
  static const String REFRESH_HEAD_LOADING = 'assets/lottie/refresh_head_loading.json';
  static const String APPLICATION_TRANSPARENT_ICON = 'assets/svg/application_transparent_icon.svg';
  static const String COLLECT = 'assets/svg/collect.svg';
  static const String COLLECT_QUIT = 'assets/svg/collect_quit.svg';
  static const String DATE_TIME = 'assets/svg/date_time.svg';
  static const String EYE_VISIBLE_ICON = 'assets/svg/eye_visible_icon.svg';
  static const String HOTWORD = 'assets/svg/hotword.svg';
  static const String HOTWORD_ITEM = 'assets/svg/hotword_item.svg';
  static const String MEDAL_BRONZE = 'assets/svg/medal_bronze.svg';
  static const String MEDAL_GOLD = 'assets/svg/medal_gold.svg';
  static const String MEDAL_SILVER = 'assets/svg/medal_silver.svg';
  static const String POINTS = 'assets/svg/points.svg';
  static const String PROGRAM = 'assets/svg/program.svg';
  static const String RUBBISH = 'assets/svg/rubbish.svg';
  static const String SEARCH = 'assets/svg/search.svg';
  static const String SHARE = 'assets/svg/share.svg';
  static const String USER_HEADER_DEFAULT_ICON = 'assets/svg/user_header_default_icon.svg';
  static const String WECHAT = 'assets/svg/wechat.svg';
}
